default: &default
  adapter: postgresql
  encoding: unicode
  pool: 16

development:
  <<: *default
  database: fabrium_development

test:
  <<: *default
  database: fabrium_test

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
